import streamlit as st
import sys
from pathlib import Path

# ====================================
# Project Path
# ====================================

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from src.predict import predict_text

# ====================================
# Page Config
# ====================================

st.set_page_config(
    page_title="AI Mental Health Triage Assistant",
    page_icon="🧠",
    layout="wide"
)

# ====================================
# Sidebar
# ====================================

st.sidebar.title("🧠 About")

st.sidebar.info(
"""
This project predicts the mental health
risk level from user text using:

- TF-IDF Vectorization
- Logistic Regression
- NLP Text Cleaning

Dataset:
Reddit Mental Health Posts
"""
)

st.sidebar.markdown("---")

st.sidebar.subheader("Risk Levels")

st.sidebar.success("🟢 Low Risk")

st.sidebar.warning("🟡 Moderate Risk")

st.sidebar.error("🔴 High Risk")

# ====================================
# Title
# ====================================

st.title("🧠 AI-Powered Mental Health Triage Assistant")

st.write(
"""
Describe how you're currently feeling.

The AI model will estimate a **risk level**
and provide general recommendations.

⚠ **This tool is for educational purposes only.**
"""
)

# ====================================
# Example Inputs
# ====================================

examples = {
    "😊 Low Risk":
        "I've been a little stressed because of work but I'm managing okay.",

    "😟 Moderate Risk":
        "I feel anxious every day and I have difficulty sleeping.",

    "🚨 High Risk":
        "I feel hopeless and don't want to continue living anymore."
}

selected_example = st.selectbox(
    "Try an example",
    ["None"] + list(examples.keys())
)

if selected_example != "None":
    default_text = examples[selected_example]
else:
    default_text = ""

# ====================================
# User Input
# ====================================

text = st.text_area(
    "Describe how you're feeling",
    value=default_text,
    height=180
)

# ====================================
# Recommendations
# ====================================

recommendations = {

    "Low Risk": [

        "Maintain a healthy sleep schedule.",

        "Exercise regularly.",

        "Practice mindfulness or meditation.",

        "Stay socially connected."
    ],

    "Moderate Risk": [

        "Talk with a trusted friend or family member.",

        "Consider speaking with a mental health professional.",

        "Practice stress management techniques.",

        "Monitor how you're feeling over time."
    ],

    "High Risk": [

        "Please seek immediate support from a qualified mental health professional.",

        "Reach out to someone you trust today.",

        "If you feel you are in immediate danger, contact your local emergency services."
    ]

}

# ====================================
# Prediction
# ====================================

if st.button("🔍 Analyze"):

    if text.strip() == "":

        st.warning("Please enter some text.")

    else:

        prediction, confidence = predict_text(text)

        st.markdown("---")

        st.subheader("Prediction")

        if prediction == "High Risk":

            st.error("🔴 HIGH RISK")

        elif prediction == "Moderate Risk":

            st.warning("🟡 MODERATE RISK")

        else:

            st.success("🟢 LOW RISK")

        st.metric(
            "Confidence",
            f"{confidence*100:.2f}%"
        )

        st.progress(float(confidence))

        st.markdown("---")

        st.subheader("Recommended Next Steps")

        for item in recommendations[prediction]:

            st.write("✅", item)

        st.markdown("---")

        with st.expander("⚠ Important Disclaimer"):

            st.write(
            """
            This application is **not** a medical diagnostic tool.

            The predictions are generated by a machine learning model trained
            on publicly available Reddit mental health posts.

            If you or someone you know may be experiencing a mental health crisis,
            please seek help from a qualified healthcare professional or contact
            your local emergency services immediately.
            """
            )

st.markdown("---")

st.caption(
    "Built using Python • Scikit-Learn • TF-IDF • Logistic Regression • Streamlit"
)